#!/usr/bin/env bash
set -Eeuo pipefail

umask 027
export LC_ALL=C

readonly RELEASE_ROOT=/opt/monday/releases/binance-lob-archiver
readonly SHADOW_LINK=/opt/monday/bin/binance-lob-archiver-shadow
readonly EVIDENCE_ROOT=/data/monday/evidence/rust-lob-shadow-preflights
readonly SERVICE_USER=hftcollector

die() {
  printf 'rust LOB shadow preflight failed: %s\n' "$*" >&2
  exit 1
}

usage() {
  printf '%s\n' \
    'Usage: monday-rust-lob-shadow-preflight <candidate-sha256> <sealed-triplet-root> <expected-replay-identity-sha256>' \
    '' \
    'The preflight binds one frozen candidate to one or more sealed triplets per market.' \
    'The expected replay identity is supplied by the reviewed corpus receipt; it is not generated by this run.' \
    'It does not replay raw frames and is not a Shadow soak, formal Gate, cutover, or Live authorization.'
}

manifest_passes() {
  local market=$1 manifest=$2 expected_dataset expected_streams
  case "$market" in
    spot)
      expected_dataset=spot_all_rust_shadow
      expected_streams='["aggTrade","bookTicker","depth@100ms","trade"]'
      ;;
    usdm)
      expected_dataset=usdm_perpetual_top100_lob_rust_shadow
      expected_streams='["bookTicker","depth@100ms"]'
      ;;
    *)
      return 1
      ;;
  esac
  jq -e --arg market "$market" --arg dataset "$expected_dataset" \
    --argjson expected_streams "$expected_streams" '
    .schema == "binance.market_tape.v2"
    and .market == $market
    and .dataset == $dataset
    and .shard_id == "all"
    and (.symbols | type) == "array" and (.symbols | length) > 0
    and .has_replay_safe_checkpoint == true
    and (.stream_types | type) == "array"
    and (.stream_types | sort) == $expected_streams
    and .stream_coverage_verified_count == (.symbols | length)
    and .all_stream_coverage_verified == true
    and ((.full_stream_coverage_verified == null) or .full_stream_coverage_verified == true)
    and .lob_continuity.contract == "binance.lob_continuity.v1"
    and .lob_continuity.sequence_gaps == 0
    and .lob_continuity.source_time_rollbacks == 0
    and .lob_continuity.declared_symbol_count == (.symbols | length)
    and .lob_continuity.covered_symbol_count == (.symbols | length)
    and .lob_continuity.missing_symbols == []
    and ((.event_types.stale_raw_trade // 0) == 0)
    and (if $market == "usdm" then
      (.event_types.book_ticker | type == "number" and . > 0)
      and ((.event_types.agg_trade // 0) == 0)
      and ((.event_types.raw_trade // 0) == 0)
      and ((.event_types.force_order // 0) == 0)
      and (has("trade_summary_contract") | not)
      and (has("trade_summaries") | not)
    else
      (.event_types.raw_trade | type == "number" and . > 0)
    end)' "$manifest" >/dev/null
}

self_test() {
  local root good stale common
  root=$(mktemp -d)
  trap 'rm -rf -- "$root"' RETURN
  good="$root/good.json"
  stale="$root/stale.json"
  common='{schema:"binance.market_tape.v2",market:"spot",dataset:"spot_all_rust_shadow",shard_id:"all",
    symbols:["BTCUSDT"],stream_types:["aggTrade","bookTicker","depth@100ms","trade"],
    stream_coverage_verified_count:1,all_stream_coverage_verified:true,
    has_replay_safe_checkpoint:true,
    lob_continuity:{contract:"binance.lob_continuity.v1",sequence_gaps:0,source_time_rollbacks:0,
      declared_symbol_count:1,covered_symbol_count:1,missing_symbols:[]},
    event_types:{raw_trade:1,stale_raw_trade:0}}'
  jq -n "$common" >"$good"
  manifest_passes spot "$good"
  jq '.event_types.stale_raw_trade = 1' "$good" >"$stale"
  if manifest_passes spot "$stale"; then
    printf 'stale raw-trade evidence unexpectedly passed preflight\n' >&2
    return 1
  fi
  printf 'shadow-preflight self-test: ok\n'
}

if [[ ${1:-} == --self-test ]]; then
  [[ $# -eq 1 ]] || {
    usage >&2
    exit 2
  }
  self_test
  exit 0
fi

[[ $# -eq 3 ]] || {
  usage >&2
  exit 2
}

for command in awk chmod cmp date dirname find grep head id install jq mktemp readelf readlink rm runuser sha256sum sort stat systemctl systemd-run tail tr wc xargs; do
  command -v "$command" >/dev/null 2>&1 || die "missing required command: $command"
done

[[ ${EUID:-$(id -u)} -eq 0 ]] || die 'must run as root'
id "$SERVICE_USER" >/dev/null 2>&1 || die "missing service user: $SERVICE_USER"

readonly CANDIDATE_SHA256=$1
readonly TRIPLET_ROOT=$2
readonly EXPECTED_REPLAY_IDENTITY_SHA256=$3
[[ $CANDIDATE_SHA256 =~ ^[a-f0-9]{64}$ ]] || die 'candidate SHA must be 64 lowercase hexadecimal characters'
[[ $EXPECTED_REPLAY_IDENTITY_SHA256 =~ ^[a-f0-9]{64}$ ]] \
  || die 'expected replay identity must be 64 lowercase hexadecimal characters'

direct_directory() {
  local path=$1
  [[ -d $path && ! -L $path && $(readlink -f -- "$path") == "$path" ]]
}

assert_no_symlink_ancestors() {
  local cursor=$1
  while [[ $cursor != / ]]; do
    if [[ -e $cursor || -L $cursor ]]; then
      [[ -d $cursor && ! -L $cursor ]] || die "path ancestor is not a direct directory: $cursor"
    fi
    cursor=${cursor%/*}
    [[ -n $cursor ]] || cursor=/
  done
}

secure_regular_file() {
  local path=$1 mode owner
  [[ -f $path && ! -L $path ]] || die "required regular file is missing or a symlink: $path"
  owner=$(stat -c %u -- "$path")
  mode=$(stat -c %a -- "$path")
  [[ $owner == 0 ]] || die "required file is not root-owned: $path"
  (( (8#$mode & 022) == 0 )) || die "required file is group/world writable: $path"
}

replay_identity_sha256() {
  local root=$1
  find "$root" -type f \( -name '*.jsonl.zst' -o -name '*.manifest.json' -o -name '*._SUCCESS' \) \
    -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}'
}

candidate_release="$RELEASE_ROOT/$CANDIDATE_SHA256"
candidate_binary="$candidate_release/binance-lob-archiver"
release_json="$candidate_release/release.json"
for path in /opt/monday /opt/monday/bin /opt/monday/releases "$RELEASE_ROOT" "$candidate_release" "$TRIPLET_ROOT"; do
  direct_directory "$path" || die "path is missing, indirect, or a symlink: $path"
done
TRIPLET_ROOT_CANONICAL=$(readlink -f -- "$TRIPLET_ROOT")
[[ $TRIPLET_ROOT_CANONICAL == "$TRIPLET_ROOT" ]] || die 'sealed-triplet root is not canonical'
assert_no_symlink_ancestors "$TRIPLET_ROOT_CANONICAL"
REPLAY_IDENTITY_BEFORE=$(replay_identity_sha256 "$TRIPLET_ROOT_CANONICAL")
[[ $REPLAY_IDENTITY_BEFORE =~ ^[a-f0-9]{64}$ ]] || die 'sealed-triplet identity hash is malformed'
[[ $REPLAY_IDENTITY_BEFORE == "$EXPECTED_REPLAY_IDENTITY_SHA256" ]] \
  || die 'sealed-triplet identity does not match the reviewed corpus digest'
secure_regular_file "$release_json"
secure_regular_file "$candidate_binary"
[[ -x $candidate_binary ]] || die 'candidate binary is not executable'
printf '%s  %s\n' "$CANDIDATE_SHA256" "$candidate_binary" | sha256sum --check --strict >/dev/null
[[ -L $SHADOW_LINK && $(readlink -f -- "$SHADOW_LINK") == "$candidate_binary" ]] \
  || die 'shadow symlink does not point to the frozen candidate'
SOURCE_REVISION=$(jq -er '.deployment_source_revision' "$release_json")
BUNDLE_SHA256=$(jq -er '.deployment_bundle_sha256' "$release_json")
BUILD_ID=$(readelf -n "$candidate_binary" | sed -n 's/.*Build ID: //p' | head -n1)
[[ $SOURCE_REVISION =~ ^[a-f0-9]{7,64}$ && $BUNDLE_SHA256 =~ ^[a-f0-9]{64}$ && $BUILD_ID =~ ^[a-f0-9]+$ ]] \
  || die 'candidate release identity is malformed'
jq -e --arg candidate "$CANDIDATE_SHA256" --arg source "$SOURCE_REVISION" --arg bundle "$BUNDLE_SHA256" \
  '.artifact_sha256 == $candidate and .deployment_source_revision == $source and .deployment_bundle_sha256 == $bundle' \
  "$release_json" >/dev/null || die 'candidate release metadata mismatch'
version_output=$(runuser --user "$SERVICE_USER" -- "$candidate_binary" --version)
[[ $version_output == "binance-lob-archiver $SOURCE_REVISION" ]] \
  || die 'candidate --version is not bound to the release source revision'
runuser --user "$SERVICE_USER" -- "$candidate_binary" --self-test >/dev/null
"$candidate_binary" --help | grep -Fq -- '--upload-only' || die 'candidate does not expose --upload-only'

strict_verifier_counter=0
strict_verifier_unit=
run_strict_verifier() {
  local status
  strict_verifier_counter=$((strict_verifier_counter + 1))
  strict_verifier_unit="monday-rust-preflight-verifier-$$-${strict_verifier_counter}.service"
  if systemd-run --quiet --wait --collect --unit="$strict_verifier_unit" \
    --uid="$SERVICE_USER" --gid="$SERVICE_USER" \
    --property=KillMode=control-group \
    --property=TimeoutStartSec=300 --property=TimeoutStopSec=30 \
    --property=MemoryHigh=5000M --property=MemoryMax=6400M \
    -- "$candidate_binary" "$@"; then
    status=0
  else
    status=$?
  fi
  systemctl stop "$strict_verifier_unit" >/dev/null 2>&1 || true
  strict_verifier_unit=
  return "$status"
}

verify_market() {
  local market=$1 root=$2
  local candidates="$root/$market-candidates.tsv" selected="$root/$market-selected.tsv"
  local manifest data success data_sha manifest_sha start_ns manifest_market file
  local -a verifier_args=()
  : >"$candidates"
  while IFS= read -r manifest; do
    secure_regular_file "$manifest"
    manifest_market=$(jq -er '.market' "$manifest")
    [[ $manifest_market == "$market" ]] || continue
    file=$(jq -er '.file' "$manifest")
    data_sha=$(jq -er '.sha256' "$manifest")
    start_ns=$(jq -er '.start_received_at_ns' "$manifest")
    [[ $file =~ ^[A-Za-z0-9._-]+\.jsonl\.zst$ && $data_sha =~ ^[a-f0-9]{64}$ && $start_ns =~ ^[0-9]+$ ]] \
      || die "$market sealed manifest has an invalid identity: $manifest"
    data="$(dirname -- "$manifest")/$file"
    success="$data._SUCCESS"
    secure_regular_file "$data"
    secure_regular_file "$success"
    printf '%s  %s\n' "$data_sha" "$data" | sha256sum --check --strict >/dev/null \
      || die "$market sealed data hash mismatch: $data"
    printf '%s\n' "$data_sha" | cmp -s - "$success" \
      || die "$market sealed _SUCCESS does not match data SHA: $success"
    manifest_passes "$market" "$manifest" \
      || die "$market sealed manifest is not replay-safe or has stale raw-trade evidence: $manifest"
    manifest_sha=$(sha256sum "$manifest" | awk '{print $1}')
    printf '%s\t%s\t%s\t%s\n' "$start_ns" "$data" "$data_sha" "$manifest_sha" >>"$candidates"
  done < <(find "$TRIPLET_ROOT" -type f -name '*.manifest.json' -print | sort)
  [[ $(wc -l <"$candidates" | tr -d ' ') -ge 1 ]] \
    || die "$market needs at least one sealed triplet"
  sort -n -k1,1 "$candidates" | tail -n 1 | sort -n -k1,1 >"$selected"
  while IFS=$'\t' read -r start_ns data data_sha manifest_sha; do
    verifier_args+=(--verify-segment "$data" --segment-content-sha256 "$data_sha" \
      --segment-manifest-sha256 "$manifest_sha")
  done <"$selected"
  run_strict_verifier --require-lob-continuity "${verifier_args[@]}" \
    || die "$market sealed-triplet LOB continuity verification failed"
  if [[ $market == spot ]]; then
    run_strict_verifier --verify-aggregate-trade-continuity "${verifier_args[@]}" \
      || die "$market sealed-triplet aggregate-trade continuity verification failed"
    run_strict_verifier --verify-raw-trade-continuity "${verifier_args[@]}" \
      || die "$market sealed-triplet raw-trade continuity verification failed"
  fi
}

tmp_dir=$(mktemp -d)
trap 'rm -rf -- "$tmp_dir"' EXIT
verify_market spot "$tmp_dir"
verify_market usdm "$tmp_dir"
REPLAY_IDENTITY_AFTER=$(replay_identity_sha256 "$TRIPLET_ROOT_CANONICAL")
[[ $REPLAY_IDENTITY_AFTER == "$REPLAY_IDENTITY_BEFORE" \
  && $REPLAY_IDENTITY_AFTER == "$EXPECTED_REPLAY_IDENTITY_SHA256" ]] \
  || die 'sealed-triplet identity changed during preflight verification'

preflight_run_id="$(date -u +%Y%m%dT%H%M%SZ)-$$"
evidence_dir="$EVIDENCE_ROOT/$CANDIDATE_SHA256/$preflight_run_id"
install -d -m 0750 "$EVIDENCE_ROOT" "$EVIDENCE_ROOT/$CANDIDATE_SHA256" "$evidence_dir"
direct_directory "$EVIDENCE_ROOT" || die 'preflight evidence root is indirect'
direct_directory "$EVIDENCE_ROOT/$CANDIDATE_SHA256" || die 'preflight candidate evidence root is indirect'
direct_directory "$evidence_dir" || die 'preflight evidence path is indirect'
assert_no_symlink_ancestors "$evidence_dir"
replay_identity=$REPLAY_IDENTITY_AFTER
triplet_identity_sha256=$(printf '%s\n' "$TRIPLET_ROOT_CANONICAL" "$replay_identity" \
  | sha256sum | awk '{print $1}')
jq -n --arg run_id "$preflight_run_id" --arg finished_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg candidate_sha256 "$CANDIDATE_SHA256" --arg source_revision "$SOURCE_REVISION" \
  --arg deployment_bundle_sha256 "$BUNDLE_SHA256" --arg build_id "$BUILD_ID" \
  --arg triplet_root "$TRIPLET_ROOT_CANONICAL" --arg replay_identity_sha256 "$replay_identity" \
  --arg expected_replay_identity_sha256 "$EXPECTED_REPLAY_IDENTITY_SHA256" \
  --arg triplet_identity_sha256 "$triplet_identity_sha256" \
  '{schema:"monday.rust_lob_shadow_preflight.v1",result:"passed",formal_gate:false,cutover:false,live:false,
    run_id:$run_id,finished_at:$finished_at,candidate_sha256:$candidate_sha256,
    source_revision:$source_revision,deployment_bundle_sha256:$deployment_bundle_sha256,
    build_id:$build_id,triplet_root:$triplet_root,
    expected_replay_identity_sha256:$expected_replay_identity_sha256,
    replay_identity_sha256:$replay_identity_sha256,
    triplet_identity_sha256:$triplet_identity_sha256,
    checks:{candidate_identity:true,sealed_triplets:true,strict_verifier:true,
      lob_continuity:true,aggregate_trade_continuity:true,raw_trade_continuity:true}}' \
  >"$evidence_dir/preflight.json"
chmod 0640 "$evidence_dir/preflight.json"
secure_regular_file "$evidence_dir/preflight.json"
printf 'preflight passed; receipt=%s\n' "$evidence_dir/preflight.json"
