apiVersion: 1

datasources:
  - name: Redis
    uid: redis
    type: redis-datasource
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      client: standalone
      addr: ${REDIS_ADDR:redis:6379}
      poolSize: 10
      timeout: 10
      pingInterval: 10
    secureJsonData:
      password: ${REDIS_PASSWORD:}

