apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
type: Opaque
stringData:
  CLICKHOUSE_URL: "https://kcveg5xfsi.ap-northeast-1.aws.clickhouse.cloud:8443"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_PASSWORD: "s9wECb~NGZPOE"

