generated_at: 2026-07-15T15:29:16.620742+00:00
source: https://api.binance.com/api/v3/exchangeInfo
instruments_sha256: 66f8010efc28efa8ad5612004826c9c581ced7964a81f5f7d2372aff3ba69c07
instruments:
- symbol: MUBUSDT
  venue: BINANCE_TOKENIZED_SECURITIES
  base: MUB
  quote: USDT
  asset_class: TokenizedSecurity
  product_type: TokenizedSecuritySpot
  regulatory_profile: AdgmTokenizedSecurity
  underlying_symbol: MU
  issuer: MUB
  tick_size: '0.01000000'
  lot_size: '0.00100000'
  min_qty: '0.00100000'
  min_notional: '5.00000000'
  status: TRADING
  permissions: []
- symbol: CRCLBUSDT
  venue: BINANCE_TOKENIZED_SECURITIES
  base: CRCLB
  quote: USDT
  asset_class: TokenizedSecurity
  product_type: TokenizedSecuritySpot
  regulatory_profile: AdgmTokenizedSecurity
  underlying_symbol: CRCL
  issuer: CRCLB
  tick_size: '0.01000000'
  lot_size: '0.01000000'
  min_qty: '0.01000000'
  min_notional: '5.00000000'
  status: TRADING
  permissions: []
- symbol: NVDABUSDT
  venue: BINANCE_TOKENIZED_SECURITIES
  base: NVDAB
  quote: USDT
  asset_class: TokenizedSecurity
  product_type: TokenizedSecuritySpot
  regulatory_profile: AdgmTokenizedSecurity
  underlying_symbol: NVDA
  issuer: NVDAB
  tick_size: '0.01000000'
  lot_size: '0.00100000'
  min_qty: '0.00100000'
  min_notional: '5.00000000'
  status: TRADING
  permissions: []
- symbol: SNDKBUSDT
  venue: BINANCE_TOKENIZED_SECURITIES
  base: SNDKB
  quote: USDT
  asset_class: TokenizedSecurity
  product_type: TokenizedSecuritySpot
  regulatory_profile: AdgmTokenizedSecurity
  underlying_symbol: SNDK
  issuer: SNDKB
  tick_size: '0.01000000'
  lot_size: '0.00010000'
  min_qty: '0.00010000'
  min_notional: '5.00000000'
  status: TRADING
  permissions: []
- symbol: TSLABUSDT
  venue: BINANCE_TOKENIZED_SECURITIES
  base: TSLAB
  quote: USDT
  asset_class: TokenizedSecurity
  product_type: TokenizedSecuritySpot
  regulatory_profile: AdgmTokenizedSecurity
  underlying_symbol: TSLA
  issuer: TSLAB
  tick_size: '0.01000000'
  lot_size: '0.00100000'
  min_qty: '0.00100000'
  min_notional: '5.00000000'
  status: TRADING
  permissions: []
